import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import org.apache.hadoop.io.BooleanWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.io.Writable;

public class PostTuple implements Writable {
	private BooleanWritable question;
	private BooleanWritable solved;
	private Text tag;
	
	public BooleanWritable getQuestion() {
		return question;
	}

	public void setQuestion(BooleanWritable question) {
		this.question = question;
	}

	public BooleanWritable getSolved() {
		return solved;
	}

	public void setSolved(BooleanWritable solved) {
		this.solved = solved;
	}

	public Text getTag() {
		return tag;
	}

	public void setTag(Text tag) {
		this.tag = tag;
	}

	public PostTuple() {
		question = new BooleanWritable();
		solved = new BooleanWritable();
		tag = new Text();
	}
	
	public void readFields(DataInput in) throws IOException {
		question.readFields(in);
		solved.readFields(in);
		tag.readFields(in);		
	}
	public void write(DataOutput out) throws IOException {
		question.write(out);
		solved.write(out);
		tag.write(out);
	}
		
	
	@Override
	public int hashCode() {//auto generated by Eclipse
		final int prime = 31;
		int result = 1;
		result = prime * result + ((question == null) ? 0 : question.hashCode());
		result = prime * result + ((solved == null) ? 0 : solved.hashCode());
		result = prime * result + ((tag == null) ? 0 : tag.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {//auto generated by Eclipse
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PostTuple other = (PostTuple) obj;
		if (question == null) {
			if (other.question != null)
				return false;
		} else if (!question.equals(other.question))
			return false;
		if (solved == null) {
			if (other.solved != null)
				return false;
		} else if (!solved.equals(other.solved))
			return false;
		if (tag == null) {
			if (other.tag != null)
				return false;
		} else if (!tag.equals(other.tag))
			return false;
		return true;
	}	

}
